# version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgresCRM
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Europe/Kyiv
    ports:
      - '${DB_PORT}:5432'
    restart: unless-stopped
    volumes:
      - postgresCRM_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgresCRM_data: